// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewignjyqmoiikvbldczp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3aWduanlxbW9paWt2YmxkY3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTIzNjgsImV4cCI6MjA3MzUyODM2OH0.1Vz1rLBbPw7aBbUq43nqjTC8YWNdDUEBw0Lq0EpoUb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});